### ISSUE TITLE
Include Deployment details in README.md file

### ISSUE THREAD

**Issue by shashankshet** [Adrinlol/landy-react-template#35]
Please add some free ways to deploy the webApp.
Eg: Maybe steps to deploy the webapp in github pages or Netify

**Comment by Jagtap01sumit** [comment]
i want to deploy this project vercel or netlify

**Comment by Adrinlol** [comment]
Please understand that the primary focus of this project is its functionality and readymade template, rather than deployment specifics. As you've rightly mentioned, there are many deployment services available, each with its own documentation and guidelines.

To deploy this project to [Vercel](https://vercel.com/new) or [Netlify](https://app.netlify.com/start), I recommend referring to their respective documentation, which will provide you with step-by-step instructions.
