### ISSUE TITLE
Scroll down when clicking on a button

### ISSUE THREAD

**Issue by jiaola** [Adrinlol/landy-react-template#8]
Do you have an example of how to scroll down to a section when clicking on a button or a link at the top? Thanks!

**Comment by Adrinlol** [comment]
Hi jiaola,

I was thinking about implementing scrollToSection function for this template, but since I wanted to add more pages to this SPA, I decided to postpone that, since those links would just take the user to another page.

Here is a link to an example I created on codesandbox :

https://codesandbox.io/s/scrolldown-example-react-umqi9

If you have any trouble implementing it into this template, let me know.

**Comment by jiaola** [comment]
Thanks! That's very helpful!

How would the action be defined for the buttons? I tried to add a "onclick" property to the Button on the following line but it didn't work: 

https://github.com/Adrinlol/landy-react-template/blob/master/template/src/components/ContentBlock/RightContentBlock/index.js#L26

**Comment by jiaola** [comment]
Never mind. I got it to work. Thanks again!

**Comment by Adrinlol** [comment]
Glad I could help! 

I will update the template later today.
